### ISSUE TITLE
Make DB

### ISSUE THREAD

**Issue by kwongjose** [kwongjose/CS364_Project#3]
Will need about 12 movies and corresponding data for actor table. I have a list of streaming services already listed on the program.

**Comment by kwongjose** [comment]
http://www.omdbapi.com/ This is the site i used to get the data for the other database. But if the one you got the api key for works use whatever.

**Comment by wmahmoud** [comment]
I ended up using this one because it doesn't even require a key.  I had originally not thought of using it because obtaining a key requires donations, but the key is unnecessary.  That was why I applied for the other key to begin with, woops.  Oh well, I have it if OMDB breaks or requires a donation to use in the future.

-Waleed

________________________________

**Comment by kwongjose** [comment]
Using a string[] for the title was a good idea. Kinda wish I had thought about that. Looks good! If you need help getting the ConnectionClass up and running let me know. Im never doing anything and I'm free most of the day tomorrow.
